# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            costa
tagline:          'Programmer'
description:      'Programmer'
url:              https://costa-na.github.io/
baseurl:          /

author:
  name:           'costa'
  url:            https://costa-na.github.io/

paginate:         5

# Custom vars
version:          2.1.0
gems: [jekyll-paginate, jekyll-gist]

github:	        'costa-na'
twitter:        ''
